[package]
name = "setu-timetable-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
setu_timetable = { path = "../setu_timetable" }
tokio = { version = "1.32.0", features = ["full"] }
